name: Decatur Fitness Kickboxing
favicon: null
layout_spectrum: 0.00481
typography_spectrum: 0.74781
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#116cd5'
    - '#fdfdfb'
    - '#010a07'
    - '#a1a19f'
    - '#835b33'
  brandStrength: 0.7679116129875183
  lightness: 0.01913740881718695
  saturation: 0.8592363528441638
  rhythmicContrast: 0.5764728444628417
purpose: []
